services:

  fastapi:
    build: ./fastAPI
    container_name: ml_services
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  jupyter:
    image: jupyter/base-notebook
    container_name: jupyter_notebook
    ports:
      - "8888:8888" 
    volumes:
      - ./models:/models